# Health Check Workflow Configuration
name: health-check
description: "Comprehensive project health diagnostics with actionable recommendations - explains issues and suggests fixes"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"

# Health check categories
check_categories:
  - git_status           # Git configuration and uncommitted changes
  - github_integration   # GitHub remote and sync status
  - linear_integration   # Linear project health
  - wezterm_launcher     # WezTerm launcher presence
  - bmad_installation    # BMAD installation and IDE integrations
  - dependencies         # Package dependencies up-to-date
  - test_coverage        # Test existence and coverage
  - documentation        # Documentation completeness and freshness
  - logging_system       # Unified logging setup
  - maintenance_due      # Days since last maintenance

# Priority levels for findings
priority_levels:
  critical: "🔴 CRITICAL"  # Blocks development or causes failures
  warning: "🟡 WARNING"    # Should be addressed soon
  info: "🔵 INFO"          # Nice to have, not urgent

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/health-check"
template: false # Action workflow - diagnostic only
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Skip flags for flexibility
skip_flags:
  - --skip-git
  - --skip-linear
  - --skip-bmad
  - --skip-deps
  - --skip-tests
  - --skip-docs
  - --skip-logs
  - --skip-maintenance
  - --quick   # Only critical checks

# Output configuration
# This is a diagnostic workflow - no files created, only reports issues

standalone: true
