# Archive Project Workflow Configuration
name: archive-project
description: "Retire old projects - comprehensive archival with pre-checks, data export, and cleanup"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"

# Archive configuration
archive_location: "~/Documents/archived"
archive_naming: "{date}-{project-name}"  # e.g., 2025-11-02-my-project
compression: "tar.gz"  # tar.gz, zip, or none

# Pre-archive checks (all required)
pre_checks:
  - uncommitted_changes    # Git status must be clean or user acknowledges
  - open_linear_issues     # Warn about open issues
  - recent_activity        # Warn if commits in last 30 days
  - unpushed_commits       # Warn about unpushed work
  - running_processes      # Check for running dev servers, databases

# Data export
export_data:
  - linear_issues          # Export all issues to JSON
  - git_metadata           # Export branch list, commit history summary
  - project_stats          # LOC, file counts, dependencies
  - documentation          # Copy all .md files to archive root
  - configuration          # Copy .env.example, config files (no secrets)

# Cleanup operations
cleanup_operations:
  - remove_from_wezterm    # Remove project from WezTerm launcher
  - close_linear_project   # Set Linear project to "Canceled" state
  - remove_from_ide        # Remove from recent projects in Claude Code/Codex
  - clear_caches           # Delete node_modules, __pycache__, build artifacts

# Archive metadata
metadata_file: "ARCHIVE_METADATA.json"
metadata_fields:
  - archive_date
  - project_name
  - project_path_original
  - git_remote_url
  - linear_project_id
  - last_commit_date
  - last_modified_date
  - file_count
  - total_size
  - archive_reason         # User-provided reason
  - restoration_notes      # How to restore if needed

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/archive-project"
template: false # Action workflow
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Skip flags - DISCOURAGED, archival should be comprehensive
skip_flags:
  - --skip-checks          # Skip pre-archive checks (DANGEROUS)
  - --skip-export          # Skip data export (not recommended)
  - --skip-cleanup         # Skip cleanup operations (not recommended)
  - --dry-run              # Preview only, no archival
  - --force                # Archive even with warnings

# Output configuration
output:
  verbosity: "moderate"              # Explain what's happening
  show_warnings: true                # Always show warnings
  confirmation_required: true        # Always require explicit confirmation
  archive_log: "{archive_location}/{archive_name}/archive.log"

standalone: true
