name: sync-and-compile
description: "Sync pre-compiled BMAD agents and workflows from central template repository for immediate use"
author: "BMad"

config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"

# Template repository configuration
agent_customisations_repo: "~/Documents/raegis_labs/agent_customisations"
templates_base_path: "{agent_customisations_repo}/bmad"

# Modules to sync (core/cis come from NPM, custom modules below)
# Custom modules: bmm (Atlas), bmb (Builder), bmm-plus (PM/SM/TEA/Dev/Analyst/UX), project-ops (Stewards)
sync_modules:
  - bmm  # Custom BMM agents (Atlas, etc.)
  - bmb  # BMad Builder agent and workflows
  - bmm-plus  # Extended agents (PM, SM, TEA, Developer, Analyst, UX Designer) and Linear workflows
  - project-ops  # Custom steward agents (docs, linear, test)

installed_path: "{project-root}/bmad/bmm/workflows/sync-and-compile"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Sync configuration
sync_agents: true
sync_workflows: true
auto_compile: true
preserve_local: true  # Preserve *.local.* files

standalone: true
