# Brownfield Setup Workflow Configuration
name: brownfield-setup
description: "Intelligent gap-filling for existing projects - adds missing setup (Git, GitHub, Linear, WezTerm, BMAD, docs) based on what's already present"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"

# Agent customisations repository for template fetching
agent_customisations_repo: "https://github.com/johnpates/agent_customisations"
agent_customisations_branch: "main"

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/brownfield-setup"
template: false # Action workflow - no document template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Detection configuration
detect_components:
  - git           # Check for .git directory
  - github        # Check for GitHub remote
  - linear        # Check for Linear project link
  - wezterm       # Check if project in WezTerm launcher
  - bmad          # Check for .bmad directory
  - bmad_ide_integrations  # Check for Claude Code, Codex, Gemini CLI configs
  - foundation_docs  # Check for idea.md, CLAUDE.md, AGENTS.md, README.md

# Skip flags for flexibility
skip_flags:
  - --skip-git      # Skip git initialization
  - --skip-bmad     # Skip BMAD installation
  - --skip-github   # Skip GitHub repo creation
  - --skip-docs     # Skip foundation documents
  - --skip-linear   # Skip Linear project creation
  - --skip-wezterm  # Skip WezTerm launcher update
  - --dry-run       # Preview without executing

# Output configuration
# This is an action workflow - applies missing setup to existing project
# No single output file, multiple artifacts created

standalone: true
