# Post-Dev Setup Workflow Configuration
name: post-dev-setup
description: "Setup after frontend/backend created - configures ports, logging, and CLI menu for operational projects"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"

# Port assignment configuration
port_range:
  min: 4000
  max: 4999

port_offsets:
  WEB_PORT: 0      # Base + 0 (frontend)
  API_PORT: 1      # Base + 1 (backend)
  DB_PORT: 2       # Base + 2 (database)
  DOCS_PORT: 3     # Base + 3 (documentation)
  WS_PORT: 4       # Base + 4 (websocket)

# Helper scripts paths
helper_scripts:
  portbase: "~/bin/portbase"
  add_proj: "~/bin/add_proj"

# Traefik proxy configuration
traefik_config:
  compose_file: "~/dev-proxy/docker-compose.yml"
  dynamic_config: "~/dev-proxy/traefik_dynamic.yml"

# Logging configuration
logging:
  log_dir: ".logs"
  main_file: ".logs/all.ndjson"
  inbox_dir: ".logs/inbox"
  redaction_file: ".logs/redaction.json"

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/post-dev-setup"
template: false # Action workflow - no document template
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Skip flags for flexibility
skip_flags:
  - --skip-ports      # Skip port assignment
  - --skip-logs       # Skip logging setup
  - --skip-cli        # Skip CLI menu creation
  - --skip-traefik    # Skip Traefik proxy setup
  - --dry-run         # Preview without executing

# Output configuration
# This is an action workflow - creates operational files in project
# No single output file, multiple artifacts created

standalone: true
