# Maintenance Workflow Configuration
name: maintenance
description: "Clean up and sync operations with preview - runs cleanup and sync tasks with category-by-category confirmation"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"

# Cleanup categories
cleanup_categories:
  - dead_code         # Unused imports, commented code, unreachable code
  - old_branches      # Merged or stale git branches
  - stale_deps        # Outdated or unused dependencies
  - old_logs          # Logs older than 30 days
  - temp_files        # .DS_Store, *.tmp, __pycache__, node_modules cache

# Sync categories
sync_categories:
  - agent_templates   # Sync from agent_customisations repo
  - bmad_framework    # Update BMAD core if newer version available
  - linear_settings   # Sync Linear labels, states, templates
  - foundation_docs   # Update idea.md, CLAUDE.md templates

# Maintenance tracking
last_maintenance_file: "{project-root}/.bmad/last-maintenance"
warning_threshold_days: 30

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/maintenance"
template: false # Action workflow
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Skip flags for flexibility
skip_flags:
  - --skip-cleanup
  - --skip-sync
  - --skip-dead-code
  - --skip-branches
  - --skip-deps
  - --skip-logs
  - --skip-temp
  - --skip-agent-templates
  - --skip-bmad
  - --skip-linear
  - --skip-docs
  - --dry-run   # Preview only, no changes
  - --yes       # Skip confirmations (auto-approve all)

# Output configuration
output:
  preview_format: "diff"  # Show changes as diff/summary
  verbosity: "moderate"    # Not silent, not chatty
  summary_file: "{project-root}/.bmad/last-maintenance-summary.md"

standalone: true
