# Sync Standards Workflow Configuration
name: sync-standards
description: "Update from templates silently - syncs agent templates, BMAD framework, workflows, and standards with minimal prompts"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"

# Sync sources
sync_sources:
  agent_templates:
    source: "~/Documents/raegis_labs/agent_customisations/templates/agents"
    target: "{project-root}/.bmad/expansion-packs/*/agents"
    preserve_pattern: "*.local.*"

  bmad_framework:
    source: "~/Documents/raegis_labs/agent_customisations/templates/bmad"
    target: "{project-root}/bmad"
    preserve_pattern: "config.yaml"

  workflows:
    source: "~/Documents/raegis_labs/agent_customisations/templates/workflows"
    target: "{project-root}/.bmad/expansion-packs/*/workflows"
    preserve_pattern: "*.local.*"

  code_style:
    source: "~/Documents/raegis_labs/agent_customisations/templates/code-style"
    target: "{project-root}"
    files: [".editorconfig", ".prettierrc", ".eslintrc.js", "pyproject.toml"]

  github_workflows:
    source: "~/Documents/raegis_labs/agent_customisations/templates/github"
    target: "{project-root}/.github/workflows"
    preserve_pattern: "*.local.yml"

# Conflict handling
conflict_strategy: "prompt"  # prompt, skip, overwrite
conflict_threshold: 10       # Auto-skip if > 10 conflicts (too many to review)

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/sync-standards"
template: false # Action workflow
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Skip flags for flexibility
skip_flags:
  - --skip-agents
  - --skip-bmad
  - --skip-workflows
  - --skip-code-style
  - --skip-github
  - --force          # Overwrite conflicts without prompting
  - --dry-run        # Preview only, no changes

# Output configuration
output:
  verbosity: "silent"        # Only errors and conflicts
  show_summary: true         # Final summary of changes
  log_file: "{project-root}/.bmad/last-sync-standards.log"

standalone: true
