# Quick Setup Workflow Configuration
name: quick-setup
description: "One-shot greenfield project initialization with directory scaffolding, Git/GitHub setup, foundation docs, BMAD v6 installation, and template syncing"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"

# Agent customisations repository for template fetching
agent_customisations_repo: "https://github.com/johnpates/agent_customisations"
agent_customisations_branch: "main"

# Module path and component files
installed_path: "{project-root}/bmad/bmm/workflows/quick-setup"
template: false # Action workflow - no document template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Project detection and configuration
project_types:
  - software
  - data-science
  - writing
  - business
  - design

# Standard directory structure
standard_dirs:
  - src/
  - tests/
  - docs/
  - .bmad/
  - .claude/commands/

# Foundation documents
foundation_docs:
  - idea.md
  - CLAUDE.md
  - AGENTS.md
  - README.md

# Skip flags for flexibility
skip_flags:
  - --skip-git      # Skip git initialization
  - --skip-bmad     # Skip BMAD installation
  - --skip-github   # Skip GitHub repo creation
  - --skip-docs     # Skip foundation documents
  - --skip-sync     # Skip template sync
  - --skip-linear   # Skip Linear project creation
  - --skip-wezterm  # Skip WezTerm launcher update
  - --dry-run       # Preview without executing

# Output configuration
# This is an action workflow - creates files directly in target project
# No single output file, multiple artifacts created

standalone: true
